version: "3.8"

services:
  auth_api:
    container_name: auth_api
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - auth_network
  redis:
    image: redis:6.2.6-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge